# [build-system]
# requires = ["hatchling"]
# build-backend = "hatchling.build"

[project]
name = "TextBlaster"
authors = [{ name = "Ravi Terala", email = "rterala@gmail.com" }]
readme = "README.md"
requires-python = ">=3.12"
description = "Text Blaster"
version = "0.1.0"
# dynamic = ["version", "description"]
dependencies = ["fastapi", "openapi", "pandas", "vonage"]

# [tool.setuptools]
# disable-wheel = true

[project.optional-dependencies]
test = ["pytest", "assertpy", "httpx", "coverage"]
dev = [
    "black",
    # "propspector[with_pyroma, with_vulture, with_bandit, with_pyright]",
]

[tool.pytest.ini_options]
# rootdir = "src"
pythonpath = ["src"]
testpaths = ["tests"]
